"""empty message

Revision ID: c205187556ef
Revises: 26a3d32f46ef
Create Date: 2022-12-22 12:37:09.179805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c205187556ef'
down_revision = '26a3d32f46ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Show', 'Venue', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Genre', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    # ### end Alembic commands ###
